### ISSUE TITLE
Bug - Tabela de Metadados

### ISSUE THREAD

**Issue by cibelecastelo** [felipeeeantunes/udacity_live#1]
Olá Felipe,

Ao rodar e analisar o seu código, percebi que a variável "varname" da tabela de metadados, encontra-se fora da linha das colunas. Por este motivo, faço uma sugestão de alteração no código da função get_meta:
De: meta.set_index('varname', inplace=True) 
Para : meta.set_index('varname', inplace=False)

**Comment by felipeeeantunes** [comment]
Oi Cibele, obrigado pelo relato. No mesmo você aponta que a variável 'varname' encontra-se fora na linha das columnas e sugere, através da alteração do parâmetro 'inplace' do método 'set_index', uma possível correção. 

No formato atual, 'varname' é o índice da tabela de metadados. Sem prejuízo, o mesmo é acessado na criação de listas de índices, como em:

`meta_data[(meta_data.level == 'ordinal') & (meta_data.keep)].index`

A chamada do exemplo tem como objetivo criar uma lista de índices, que fazer referência às colunas que desejamos selecionar. Esta lista indexada é acessada posteriormente em tratamentos específicos para cada level de metadados. 

A alteração do parâmetro 'inplace', de True para False, implicaria em alterar tais chamadas. Por outro lado, manter em mesmo estado não causa prejuízo ao código. 

Diante disso, não vejo motivo para alterações.
Obrigado.
